### ISSUE TITLE
Possible future issues with lsmeans

### ISSUE THREAD

**Issue by rvlenth** [CDEager/nauf#3]
Just to advise you that I made some significant additions to **lsmeans** so that it detects and handles nested structures in the fixed-effects part of models. It seems like this could potentially make what **nauf** does easier to do, since the types of situations you describe are in fact nested factors. 

But it could also complicate the existing package. In order to ensure that existing code plays along with **lsmeans**, I suggest that you insert this code just after any call to `lsmeans::ref.grid`:
```
rg@model.info$nesting <- NULL
```
(where `rg` is the ref.grid just created). Other ways of handling this are to include the new `nesting` argument in the `ref.grid` call, or to `update` it afterward; but both of these approaches would require the newest version of **lsmeans**.

Also, I discovered that the version 2.27 of **lsmeans** I submitted to CRAN had inadvertently broken **nauf**. I have fixed that and will re-submit it to CRAN.

**Comment by CDEager** [comment]
I've added the suggested line of code in commit 8af8ebf
